"""Immutable, one-node OpenCode work packages and fail-closed candidate checks."""

import argparse
from copy import deepcopy
from datetime import date
import json

from .confidence import claim_slots
from .knowledge_validation import knowledge_errors
from .research_contract import file_hash, methodology_hash
from .research_profile import fingerprint, research_policy
from .run_baseline import baseline_errors
from .storage import Repository, contained_path, read_yaml, write_json

TASKS_DIR = "output/research/tasks"


def task_inputs(repo, feature_id):
    features = repo.features()
    _, paths = repo.knowledge()
    return {"feature": fingerprint(features[feature_id]), "config": fingerprint(repo.config()),
            "policy": fingerprint(research_policy(repo)), "methodology": methodology_hash(repo.root),
            "knowledge": file_hash(repo.root / paths[feature_id]),
            "baseline": file_hash(repo.root / "output/research/baseline.json")}


def prepare_task(repo, feature_id, model, run_date):
    date.fromisoformat(run_date)
    if not model or "/" not in model:
        raise ValueError("Use an explicit provider/model")
    features = repo.features()
    knowledge, paths = repo.knowledge()
    if feature_id not in features:
        raise ValueError(f"Unknown feature: {feature_id}")
    # Candidate packages are regenerated by the author; their timestamps are not
    # semantic task inputs. Referenced source hashes are checked at submission.
    context = repo.root / "output/contexts" / (feature_id + ".json")
    if not context.exists():
        raise ValueError(f"Missing context: run official_docs.py context {feature_id}")
    inputs = task_inputs(repo, feature_id)
    identity = {"feature_id": feature_id, "model": model, "run_date": run_date, "inputs": inputs}
    task_id = fingerprint(identity)
    directory = f"{TASKS_DIR}/{task_id}"
    errors = baseline_errors(repo, repo.config(), research_policy(repo), run_date)
    package = {"schema_version": 1, "task_id": task_id, **identity,
               "mode": "diagnostic_pilot" if errors else "research_candidate",
               "baseline_errors": errors, "knowledge_path": paths[feature_id],
               "context_path": context.relative_to(repo.root).as_posix(),
               "candidate_path": directory + "/candidate.yaml",
               "report_path": directory + "/worker-report.md",
               "contract": "docs/opencode-worker-contract.md",
               "claim_ids": [key for key, *_ in claim_slots(features[feature_id], knowledge[feature_id], repo.config()["platforms"])],
               "budget": {"max_bodies": 15, "max_fetches": 6, "max_attempts": 1,
                          "hard_provider_cost_cap": False},
               "production_write_authorized": False}
    path = repo.root / directory / "task.json"
    if path.exists() and json.loads(path.read_text()) != package:
        raise ValueError("Immutable task collision; do not overwrite")
    write_json(path, package)
    return path, package


def load_task(repo, path):
    path = contained_path(repo.root, str(path), TASKS_DIR)
    task = json.loads(path.read_text(encoding="utf-8"))
    expected = fingerprint({key: task[key] for key in ("feature_id", "model", "run_date", "inputs")})
    if task["task_id"] != expected or path.parent.name != expected or path.name != "task.json":
        raise ValueError("Task identity does not match its contents/path")
    for key, filename in (("candidate_path", "candidate.yaml"), ("report_path", "worker-report.md")):
        if contained_path(repo.root, task[key], TASKS_DIR) != path.parent / filename:
            raise ValueError(f"Task {key} must remain inside its own directory")
    if task.get("production_write_authorized") is not False:
        raise ValueError("Worker cannot grant itself production write authority")
    return task


def candidate_errors(repo, task, candidate):
    fid = task["feature_id"]
    errors = []
    if task["inputs"] != task_inputs(repo, fid):
        errors.append("Task inputs changed; create a new task and re-review, do not resume stale output")
    if candidate.get("feature_id") != fid:
        return errors + ["Candidate belongs to a different feature"]
    features = repo.features()
    knowledge, paths = repo.knowledge()
    knowledge = deepcopy(knowledge)
    knowledge[fid] = candidate
    config = repo.config()
    errors.extend(knowledge_errors(repo, features, knowledge, paths, config))
    if errors:
        return errors
    current_baseline_errors = baseline_errors(repo, config, research_policy(repo), task["run_date"])
    for key, _, _, _, claim in claim_slots(features[fid], candidate, config["platforms"]):
        if not claim.get("assessment"):
            errors.append(f"{key}: investigated slot needs assessment")
        if claim.get("status", claim.get("result")) == "unknown":
            if not claim.get("rationale") or not claim.get("missing_requirements"):
                errors.append(f"{key}: unknown needs investigation rationale and concrete missing_requirements")
        elif claim.get("verification") != "confirmed":
            errors.append(f"{key}: incomplete finding must remain unknown, not an asserted result")
        if current_baseline_errors and (claim.get("verification") == "confirmed" or
                claim.get("assessment", {}).get("confidence") in ("high", "medium")):
            errors.append(f"{key}: unresolved launch baseline forbids confirmation/high-medium confidence")
    if not current_baseline_errors:
        baseline = json.loads((repo.root / "output/research/baseline.json").read_text())
        for platform, presence in candidate["presence"].items():
            expected = baseline["platforms"][platform]["context"]
            for key in ("release", "sdk", "distribution", "device_forms"):
                if presence.get("context", {}).get(key) != expected[key]:
                    errors.append(f"{platform}: candidate {key} differs from launch baseline")
    return errors


def check_task(repo, path):
    task = load_task(repo, path)
    candidate_path = repo.root / task["candidate_path"]
    candidate = read_yaml(candidate_path)
    errors = candidate_errors(repo, task, candidate)
    if not (repo.root / task["report_path"]).is_file():
        errors.append("Worker report missing")
    result = {"task_id": task["task_id"], "candidate_sha256": file_hash(candidate_path),
              "structurally_valid": not errors, "semantic_review_passed": False,
              "production_accepted": False, "errors": errors}
    return result


def main(argv=None):
    parser = argparse.ArgumentParser(description=__doc__)
    commands = parser.add_subparsers(dest="command", required=True)
    prepare = commands.add_parser("prepare")
    prepare.add_argument("--feature", action="append", required=True)
    prepare.add_argument("--model", required=True)
    prepare.add_argument("--run-date", default=date.today().isoformat())
    check = commands.add_parser("check")
    check.add_argument("task")
    args = parser.parse_args(argv)
    repo = Repository()
    try:
        if args.command == "prepare":
            for fid in dict.fromkeys(args.feature):
                path, task = prepare_task(repo, fid, args.model, args.run_date)
                print(json.dumps({"task": str(path), "mode": task["mode"]}, ensure_ascii=False))
            return 0
        result = check_task(repo, args.task)
        print(json.dumps(result, ensure_ascii=False, indent=2))
        return 0 if result["structurally_valid"] else 2
    except (ValueError, OSError, KeyError, TypeError, AttributeError) as exc:
        print(json.dumps({"structurally_valid": False, "error": str(exc)}, ensure_ascii=False))
        return 2
