/** Shared field labels and source-link protocol validation. */
export const labels = {
  high: "高可信",
  medium: "中可信",
  low: "低可信",
  unassessed: "未评估",
  required: "必须真机复核",
  recommended: "建议抽样复核",
  not_required: "无需真机复核",
  pending: "待实测",
  passed: "计划样本通过",
  failed: "实测不符",
  pass: "符合预期",
  fail: "不符合预期",
  inconclusive: "结果不确定",
  assessment: "置信度评估",
  confidence: "知识置信度",
  confidence_rationale: "评级依据与边界",
  device_review: "真机复核计划",
  device_requirement: "真机复核需求",
  device_state: "真机复核状态",
  requirement: "需求级别",
  reason: "复核原因",
  assessed_by: "评级者",
  assessed_at: "评级日期",
  input_hash: "评级输入指纹",
  claim_hash: "实测对应结论指纹",
  plan_hash: "测试用例指纹",
  cases: "测试用例",
  case_id: "测试用例 ID",
  device_model: "具体机型",
  os_build: "系统构建号",
  steps: "操作步骤",
  expected: "预期结果",
  observed: "实际观测",
  results: "实测结果",
  outcome: "实测判定",
  tested_by: "实测人员",
  tested_at: "实测时间",
  artifact_path: "实测材料路径",
  method: "执行方式",
  human_physical_device: "人工真机测试",
  missing_requirements: "待补证据与条件",
  facts: "结构化平台事实",
  fact: "平台事实",
  support: "平台支持",
  comparison: "平台比较",
  claim_id: "知识项 ID",
  contexts: "各平台适用环境",
  priority: "复核排序级别（0 最优先）",
  statement: "事实陈述",
  stated: "事实记录",
  unknown: "待确认",
  supported: "支持",
  conditional: "条件支持",
  full: "完整支持",
  partial: "部分支持",
  none: "无",
  unsupported: "不支持",
  not_supported: "不支持",
  not_applicable: "不适用",
  unreviewed: "未复核",
  in_review: "确认中",
  confirmed: "已确认",
  rejected: "已否决",
  stale: "已过期",
  not_started: "待确认",
  in_progress: "确认中",
  complete: "已完成",
  different: "存在差异",
  same: "行为一致",
  has_confirmed_differences: "有已确认差异",
  confirmed_same: "已确认一致",
  stub: "待补充",
  draft: "草稿",
  reviewed: "正文已整理",
  leaf: "叶子节点",
  rollup: "分支节点",
  android: "Android",
  ios: "iOS",
  harmonyos: "HarmonyOS",
  os: "操作系统",
  phone: "手机",
  tablet: "平板",
  id: "ID",
  feature_id: "节点 ID",
  role: "角色",
  status: "状态",
  verification: "确认状态",
  definition: "定义",
  name: "名称",
  zh: "中文",
  en: "英文",
  parent: "父节点",
  children: "子节点",
  child_index: "子节点索引",
  knowledge_role: "节点角色",
  layer: "所属层",
  device_forms: "设备形态",
  privacy_class: "隐私类别",
  aliases: "别名",
  notes: "说明",
  bindings: "精选 API 绑定",
  knowledge_path: "知识文件",
  comparison_scope: "比较范围",
  includes: "纳入范围",
  excludes: "排除范围",
  comparison_dimensions: "比较维度",
  split_justification: "拆分依据",
  leaf_at_this_level: "在当前层结束",
  schema_version: "数据版本",
  subject_hash: "范围指纹",
  programming_model: "编程模型",
  lifecycle_background: "生命周期与后台",
  permissions_privacy: "权限与隐私",
  limits_precision: "限制与精度",
  api_surface: "API 形态",
  architecture_diff: "架构差异",
  availability: "支持范围",
  porting_traps: "迁移注意事项",
  unique_extensions: "平台扩展",
  legacy_presence: "历史支持判断",
  legacy_definition: "历史定义",
  migration_notes: "迁移记录",
  baseline: "版本基线",
  context: "运行上下文",
  rationale: "判断依据",
  scope: "适用范围",
  evidence_refs: "证据引用",
  platform: "平台",
  platforms: "平台",
  dimension: "比较维度",
  result: "比较结论",
  summary: "摘要",
  from: "来源平台",
  to: "目标平台",
  trap: "注意事项",
  cross_ref: "相关节点",
  kind: "类型",
  since: "起始版本",
  note: "备注",
  url: "来源链接",
  syscap: "系统能力",
  title: "标题",
  local_path: "本地来源",
  sha256: "内容校验值",
  source: "来源",
  source_type: "来源类型",
  missing_subcapabilities: "缺失子能力",
  evidence: "证据",
  comparisons: "比较记录",
  checked_at: "核实日期",
  accessed_at: "访问日期",
  reviewed_at: "复核日期",
  version: "版本",
  verified_at: "确认日期",
  verified_by: "确认人",
  conditions: "适用条件",
  release: "系统版本",
  sdk: "SDK 版本",
  distribution: "发行版",
  locator: "证据位置",
  revision: "修订版本",
  applies_to: "适用环境",
  basis: "事实依据类型",
  official_statement: "官方明示",
  evidence_based_analysis: "基于证据的分析",
};
export const label = (value) => labels[value] ?? String(value ?? "—");
export function safeUrl(value) {
  try {
    const url = new URL(value);
    return ["http:", "https:"].includes(url.protocol) ? url.href : null;
  } catch {
    return null;
  }
}
